spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/RikkeiSoft_Workspace/Module4_Session6/Microservices
          search-paths: medical-config-repo
          default-label: main
server:
  port: 8888
